baseURL: "https://bmjxdev.github.io/bmjxDev"
languageCode: "en-us"
title: "Brice J. profile"
theme: "./.."
relativeURLs: true

googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Brice Jacobs"
  namecolor: ffc107
  profession: "DevOps Engineer"
  github: "https://github.com/bmjxDev"
  gitlab: "https://gitlab.com/bmjxDev"
  linkedin: "https://www.linkedin.com/in/brice-jacobs-24931345/"
  #twitter: "https://twitter.com/"
  #instagram: "https://instagram.com/"
  facebook: "https://facebook.com/brice.m.jacobs"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Brice, a passionate DevOps Engineer with deep analytics skills. Investigating, diagnosing system problem and knowledge of the software/hardware lifecycle. Ability to manage and execute multiple tasks as well as achieve results, while displaying strong work ethics. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
  descripe_l2_person: "This is a example template for about section. You can find my works [here](#projects)"
  skills:
    - name: CSS
      percentage: 90
    - name: Django
      percentage: 80
    - name: Hugo
      percentage: 80
    - name: React JS
      percentage: 75
    - name: Angular
      percentage: 75
    - name: Java
      percentage: 90
    - name: Python
      percentage: 85
    - name: Bash scripting
      percentage: 80
    - name: Electron JS
      percentage: 75
    - name: CSS
      percentage: 90
    - name: Django
      percentage: 80
    - name: Hugo
      percentage: 80
    - name: React JS
      percentage: 75
    - name: Angular
      percentage: 75
    - name: Java
      percentage: 90
    - name: Python
      percentage: 85
    - name: Bash scripting
      percentage: 80
    - name: Electron JS
      percentage: 75

  # Experience
  disable_experience: false
  experience:
    - company: "Google"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Software developer"
      startdate: Feb 2021
      enddate: present
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Facebook"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Amazon"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: false
  education:
    - degree: "Bachelors of Science"
      branch: "Information Technology"
      university: "Delaware State university"
      startedyear: "2008"
      graduation: "2013"
    - degree: "High School Diploma"
      university: "Hahnville High School"      
      startedyear: "2004"
      graduation: "2008"
    
  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "bmjxDev@outlook.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
