name = "hugo-profile"
license = "MIT"
licenselink = "https://github.com/bmjxDev/bmjxDev/LICENSE"
description = "A high performance hugo theme for personal portfolio"
homepage = "https://github.com/bmjxDev"
tags = ["Responsive","Blog", "Portfolio", "Personal", "Minimal", "Clean", "Fast", "Single page", "Seo", "Google analytics"]
features = ["Highly customizable"]
min_version = "0.68.0"

[author]
  name = "Brice J"
  homepage = "https://github.com/bmjxDev"

 